### ISSUE TITLE
Please support header_libraries 2.5.3

### ISSUE THREAD

**Issue by toge** [beached/utf_range#2]
Some codes in utf_range seem not to  follow header_libraries/2.5.3.
I met following error when I compile utf_range/2.2.0 with header_libraries/2.5.3.

```
include/daw/utf_range/daw_utf_range.h:208:45: error: ‘make_string_view_it’ is not a member of ‘daw’; did you mean ‘daw::sv1::make_string_view_it’?
    return daw::make_string_view_it( raw_begin( ), raw_end( ) );
```

Cloud you fix it?

**Comment by beached** [comment]
Put some time into updating it, should be working now.  The previous release is in vcpkg and works too.

**Comment by toge** [comment]
Thank you for your quick response!
